CREATE TABLE queue (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  entered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  page_id UUID,
  CONSTRAINT fk_page FOREIGN KEY (page_id) REFERENCES pages(id)
);